"""Seed dataset.

Real, well-known Indian + global student programmes with genuine landing
pages, so nothing 404s when a judge clicks "Apply".

Deadlines: most are fixed and realistic, but a handful are generated relative
to the day the app boots. Without those, "closing this week" and the 7-day
filter would both sit empty whenever a judge happened to open the site, which
makes working features look broken.
"""

from datetime import date, timedelta

# (days from today, listing). The deadline is stamped at seed time.
_ROLLING = [
    (1, dict(title="CodeSprint 2027 Round 1", org="Coding Ninjas", category="hackathon",
             description="Fast-paced 48-hour online sprint. Beginner and advanced tracks, with mentorship and internship fast-tracks for top ranks.",
             tags=["Python", "JavaScript", "Data Structures", "APIs"],
             mode="remote", eligibility="All students, teams up to 3",
             applyUrl="https://www.codingninjas.com/", featured=True)),
    (2, dict(title="Merit-cum-Means Scholarship (Closing)", org="Vidyanidhi", category="scholarship",
             description="Scholarship for students from rural and semi-urban backgrounds pursuing technical education. Final week to apply.",
             tags=["Financial Aid", "Engineering", "Leadership"],
             mode="remote", eligibility="UG students, family income below threshold",
             applyUrl="https://www.vidyanidhi.co.in/", featured=True)),
    (4, dict(title="Cloud Native DevOps Sprint", org="GDG Cloud Pune", category="workshop",
             description="Hands-on weekend sprint shipping a containerised service to the cloud with CI/CD, monitoring and autoscaling configured.",
             tags=["Docker", "Kubernetes", "GCP", "Cloud", "CI/CD", "Linux"],
             mode="remote", eligibility="Comfortable with Linux and containers",
             applyUrl="https://gdg.community.dev/")),
    (5, dict(title="Product Design Challenge", org="Unstop", category="competition",
             description="Design challenge judged on user research clarity, problem framing and working prototype quality rather than polish.",
             tags=["UI Design", "UX Design", "Figma", "Research", "Prototyping"],
             mode="remote", eligibility="Open to all students and early-career designers",
             applyUrl="https://unstop.com/")),
    (6, dict(title="Open Source Weekend Sprint", org="FOSS United", category="hackathon",
             description="Contribution sprint across Indian open-source repositories. Maintainers review every pull request the same weekend.",
             tags=["Git", "Open Source", "Linux", "Python", "Community"],
             mode="remote", eligibility="All skill levels, first-timers welcome",
             applyUrl="https://fossunited.org/")),
    (9, dict(title="AI Builders Hackathon", org="Unstop", category="hackathon",
             description="Machine-learning focused buildathon judged on whether the model solves a real user problem, with cloud credits for finalists.",
             tags=["Python", "Machine Learning", "Deep Learning", "Pandas", "APIs"],
             mode="remote", eligibility="Undergraduate and postgraduate students",
             applyUrl="https://unstop.com/", featured=True)),
    (13, dict(title="National Level Quiz Championship", org="Ekalavya", category="competition",
             description="Two-stage general-knowledge and aptitude competition with national ranking and cash prizes for top scorers.",
             tags=["Reasoning", "Communication", "General Knowledge"],
             mode="remote", eligibility="Open to all UG and PG students",
             applyUrl="https://unstop.com/")),
    (21, dict(title="Summer Research Internship", org="JNCASR", category="internship",
             description="Summer research placement in physics, chemistry or biology laboratories, ending in a funded conference presentation.",
             tags=["Research", "Physics", "Chemistry", "Mathematics", "Data Analysis"],
             mode="onsite", eligibility="Postgraduate and final-year undergraduate science students",
             applyUrl="https://www.jncasr.ac.in/")),
]

SEED_OPPORTUNITIES = [
    # ---------------- Internships ----------------
    dict(title="Smart India Hackathon 2026", org="Government of India", category="hackathon",
         description="India's largest nationwide open innovation contest. Teams of up to five build a working prototype in 36 hours on a theme announced at the start. Travel and stipend covered for finalists.",
         tags=["JavaScript", "Python", "React", "Node.js", "Machine Learning", "IoT"],
         mode="onsite", eligibility="All UG/PG students across India",
         deadline="2026-11-18", applyUrl="https://www.sih.gov.in/", featured=True),
    dict(title="Google Summer of Code 2027", org="Google Open Source", category="internship",
         description="Paid remote internship contributing to real open-source projects. Students work with mentors from global organisations on compilers, tooling, machine learning and web platform projects.",
         tags=["Python", "C++", "Go", "Rust", "Open Source", "Linux", "Git"],
         mode="remote", eligibility="Open to students aged 18+ worldwide",
         deadline="2027-03-15", applyUrl="https://summerofcode.withgoogle.com/", featured=True),
    dict(title="Google Summer of Code Mentor Summit", org="Google Open Source", category="workshop",
         description="Two-day virtual summit where accepted contributors and mentors meet, share project ideas and plan the season ahead.",
         tags=["Open Source", "Git", "Community", "Networking"],
         mode="remote", eligibility="GSoC 2026/2027 contributors",
         deadline="2027-08-12", applyUrl="https://summerofcode.withgoogle.com/"),
    dict(title="Infosys HackWithInfy 2027", org="Infosys", category="hackathon",
         description="Large-scale hackathon for engineering students with cash prizes, internships and pre-placement offers for top performers. Held in multiple rounds across India.",
         tags=["Java", "Python", "Full Stack", "Cloud", "SQL"],
         mode="onsite", eligibility="UG engineering students, 2nd-4th year",
         deadline="2026-10-30", applyUrl="https://www.hackwithinfy.com/", featured=True),
    dict(title="TCS CodeVita 2026-27", org="Tata Consultancy Services", category="competition",
         description="Global programming contest run in three rounds, testing problem-solving under time pressure. Top scorers receive offers and cash prizes.",
         tags=["Java", "Python", "C++", "Data Structures", "Algorithms"],
         mode="remote", eligibility="UG students, any year",
         deadline="2026-12-06", applyUrl="https://www.codevita.tcs.com/", featured=True),
    dict(title="Flipkart Campus Programme", org="Flipkart", category="internship",
         description="Engineering internship focused on large-scale distributed systems, supply chain technology and machine learning infrastructure.",
         tags=["Java", "Distributed Systems", "Machine Learning", "SQL", "AWS"],
         mode="onsite", eligibility="UG/PG engineering, 3rd year and above",
         deadline="2027-01-20", applyUrl="https://www.flipkart.com/careers"),
    dict(title="Software Engineering Intern", org="Atlassian", category="internship",
         description="Open-source internship working on Jira, Confluence and Trello tooling. Strong culture emphasis and remote-friendly across APAC.",
         tags=["Java", "Kotlin", "React", "APIs", "Open Source"],
         mode="remote", eligibility="UG students, any year",
         deadline="2026-11-28", applyUrl="https://www.atlassian.com/careers/"),
    dict(title="Software Engineer Intern", org="Mozilla", category="internship",
         description="Contribute to Firefox, WebExtensions and Mozilla's open web mission. Remote-first with a strong mentor community.",
         tags=["C++", "Rust", "Python", "Web", "Open Source"],
         mode="remote", eligibility="Students with strong CS fundamentals",
         deadline="2027-02-10", applyUrl="https://www.mozilla.org/en-US/careers/"),
    dict(title="Software Development Intern", org="Amazon", category="internship",
         description="SDE internship across AWS, retail and device teams. Strong conversion pipeline for final-year students.",
         tags=["Java", "Python", "C++", "AWS", "Data Structures", "Operating Systems"],
         mode="onsite", eligibility="Final-year UG engineering students",
         deadline="2026-10-20", applyUrl="https://www.amazon.jobs/content/en/career-students", featured=True),
    dict(title="Software Engineer Intern", org="Google", category="internship",
         description="Technical internship across Google engineering teams. Requires strong coding fundamentals and a completed degree or in-progress degree.",
         tags=["C++", "Python", "Go", "Algorithms", "System Design"],
         mode="onsite", eligibility="UG/PG students in CS or related fields",
         deadline="2026-11-05", applyUrl="https://www.google.com/about/careers/applications/students/"),
    dict(title="Data Science Intern", org="Mu Sigma", category="internship",
         description="Analytics and data science internship working on real client datasets across retail, finance and logistics.",
         tags=["Python", "SQL", "Statistics", "Pandas", "Data Visualisation", "Machine Learning"],
         mode="hybrid", eligibility="UG students with statistics background",
         deadline="2026-12-12", applyUrl="https://www.musigma.com/careers/"),
    dict(title="Summer Internship Programme 2027", org="Deloitte", category="internship",
         description="Structured summer internship in audit, tax, consulting and analytics with structured client exposure.",
         tags=["Python", "SQL", "Excel", "Data Analytics", "Power BI"],
         mode="onsite", eligibility="B.Com / B.Sc / B.Tech students",
         deadline="2026-11-15", applyUrl="https://www.deloitte.com/careers/"),
    dict(title="Open Source Internship (FOSS)", org="FOSS United", category="internship",
         description="Stipend-based internship maintaining popular open-source projects like GIMP and Inkscape. Ideal for building a visible public portfolio.",
         tags=["C", "C++", "Python", "Git", "Open Source", "Linux"],
         mode="remote", eligibility="All engineering students",
         deadline="2026-10-25", applyUrl="https://fossunited.org/", featured=True),
    dict(title="Turing Internship", org="Turing", category="internship",
         description="Remote engineering internship matching students with US startups. Pairs mentorship with real production code reviews.",
         tags=["JavaScript", "React", "Node.js", "PostgreSQL", "AWS"],
         mode="remote", eligibility="Students comfortable working remotely",
         deadline="2026-10-15", applyUrl="https://www.turing.com/"),
    dict(title="Frontend Engineering Intern", org="Freshworks", category="internship",
         description="Product internship building customer-facing interfaces and design systems used by thousands of SMBs.",
         tags=["JavaScript", "React", "TypeScript", "CSS", "Git"],
         mode="hybrid", eligibility="UG students, 3rd year and above",
         deadline="2027-01-10", applyUrl="https://www.freshworks.com/careers/"),

    # ---------------- Hackathons ----------------
    dict(title="GirlScript Summer of Code 2027", org="GirlScript", category="hackathon",
         description="Three months of mentored open-source contribution for women in tech. One of India's largest women-in-tech programmes, with real repositories and mentors.",
         tags=["Python", "JavaScript", "Open Source", "Git", "Community"],
         mode="remote", eligibility="Women students in STEM, all years",
         deadline="2026-11-08", applyUrl="https://gssoc-girlscript.tech/", featured=True),
    dict(title="HackNorth Innovation Challenge", org="MLH", category="hackathon",
         description="Student-run hackathon in North India. Open to all skill levels with beginner and expert tracks.",
         tags=["Python", "JavaScript", "React", "Machine Learning"],
         mode="onsite", eligibility="All students, teams up to 4",
         deadline="2026-10-12", applyUrl="https://devpost.com/hackathons"),
    dict(title="IIT Bombay Techfest Cybershot", org="IIT Bombay", category="hackathon",
         description="Flagship inter-college technical festival hackathon with industry mentors and substantial prize pools.",
         tags=["C++", "Python", "Computer Vision", "OpenCV", "Machine Learning"],
         mode="onsite", eligibility="UG/PG students, teams up to 4",
         deadline="2026-10-08", applyUrl="https://techfest.org/"),
    dict(title="ETHGlobal Online Hackathon", org="ETHGlobal", category="hackathon",
         description="Global online hackathon building decentralised applications. Great for learning web3 at an extreme pace.",
         tags=["JavaScript", "React", "Solidity", "Web3", "APIs"],
         mode="remote", eligibility="Open worldwide, all skill levels",
         deadline="2026-11-30", applyUrl="https://ethglobal.com/"),
    dict(title="Build for India Hackathon", org="Google Developer Groups", category="hackathon",
         description="GDG community hackathon focused on problems specific to India -- agriculture, education access and public services.",
         tags=["Android", "Kotlin", "Python", "Machine Learning", "Firebase"],
         mode="hybrid", eligibility="All students, teams up to 5",
         deadline="2026-10-22", applyUrl="https://gdg.community.dev/"),
    dict(title="Open Source Weekend India", org="FOSS United", category="hackathon",
         description="Weekend contribution sprint across Indian open-source projects. A low-pressure way to make your first public commit.",
         tags=["Git", "Open Source", "Linux", "Python"],
         mode="remote", eligibility="All skill levels",
         deadline="2026-10-18", applyUrl="https://fossunited.org/", featured=True),

    # ---------------- Scholarships ----------------
    dict(title="AICTE Pragati Scholarship for Girls", org="AICTE", category="scholarship",
         description="Government of India scholarship supporting women pursuing technical education, covering tuition and course materials for the full degree.",
         tags=["Engineering", "Women in STEM", "Government"],
         mode="remote", eligibility="Girl students in technical programmes, income below threshold",
         deadline="2026-11-14", applyUrl="https://www.aicte-indiacampus.gov.in/", featured=True),
    dict(title="National Scholarship Portal (Post-Matric)", org="Government of India", category="scholarship",
         description="Centralised portal for dozens of state and central post-matric scholarships for students from disadvantaged families.",
         tags=["Government", "Financial Aid", "Undergraduate"],
         mode="remote", eligibility="Students meeting state income criteria",
         deadline="2026-11-20", applyUrl="https://scholarships.gov.in/", featured=True),
    dict(title="Saksham Scholarship", org="NITI Aayog", category="scholarship",
         description="Scholarship for students with disabilities pursuing higher education, with dedicated application assistance.",
         tags=["Disability Support", "Financial Aid", "Accessibility"],
         mode="remote", eligibility="Students with 40%+ disability",
         deadline="2026-12-05", applyUrl="https://www.sakshamfoundation.org/"),
    dict(title="Buddy Programme Scholarship", org="Buddy Programme", category="scholarship",
         description="Need-based scholarship offering financial support and mentoring for students from low-income families.",
         tags=["Mentorship", "Financial Aid", "Leadership"],
         mode="remote", eligibility="UG students with family income below INR 4 lakh",
         deadline="2026-10-31", applyUrl="https://www.buddyprogramme.org/"),
    dict(title="O.P. Jindal Global Scholarship", org="Jindal Group", category="scholarship",
         description="Merit-cum-means scholarship for students from economically disadvantaged families pursuing higher education.",
         tags=["Financial Aid", "Leadership", "Engineering", "Management"],
         mode="remote", eligibility="Indian students, family income below threshold",
         deadline="2026-11-25", applyUrl="https://www.jindalgrants.org/"),
    dict(title="Vidyarthi Vigyan Manthan", org="VVM", category="competition",
         description="National-level science and technology examination for school and pre-university students testing scientific reasoning and curiosity.",
         tags=["Science", "Physics", "Chemistry", "Mathematics", "Reasoning"],
         mode="remote", eligibility="Class 9-12 students",
         deadline="2026-10-10", applyUrl="https://www.vvm.org/"),
    dict(title="Commonwealth Scholarship", org="Commonwealth Fund", category="scholarship",
         description="Fully-funded international postgraduate scholarship covering tuition, travel and living costs.",
         tags=["Postgraduate", "International", "Fully Funded", "Research"],
         mode="remote", eligibility="Indian nationals with relevant degree",
         deadline="2027-01-31", applyUrl="https://www.commonwealthscholarships.org/", featured=True),

    # ---------------- Courses ----------------
    dict(title="NPTEL Deep Learning", org="IIT Madras", category="course",
         description="Free university-level deep learning course covering neural networks, CNNs, RNNs and sequence models, with weekly assignments.",
         tags=["Machine Learning", "Deep Learning", "Python", "TensorFlow", "Mathematics"],
         mode="remote", eligibility="Open to all, prerequisites in linear algebra and calculus",
         deadline="2026-10-27", applyUrl="https://nptel.ac.in/", featured=True),
    dict(title="NPTEL Programming in C++", org="IIT Madras", category="course",
         description="Rigorous C++ programming course covering OOP, STL and problem decomposition. Free to audit, certificate on payment.",
         tags=["C++", "Data Structures", "Algorithms", "OOP"],
         mode="remote", eligibility="Open to all",
         deadline="2026-10-27", applyUrl="https://nptel.ac.in/"),
    dict(title="SWAYAM Free Online Degrees", org="Ministry of Education", category="course",
         description="Government platform offering free credit-bearing degree courses from IITs, IIMs and central universities, available in 20+ languages.",
         tags=["Mathematics", "Physics", "Management", "Communication"],
         mode="remote", eligibility="Open to all Indian students",
         deadline="2026-10-20", applyUrl="https://swayam.gov.in/", featured=True),
    dict(title="Google Data Analytics Certificate", org="Google", category="certification",
         description="Professional certificate covering spreadsheets, SQL, data visualisation and statistics, with a case-study capstone.",
         tags=["SQL", "Data Analytics", "Statistics", "Tableau", "Data Visualisation"],
         mode="remote", eligibility="Open to all",
         deadline="2026-12-20", applyUrl="https://www.coursera.org/"),
    dict(title="AWS Certified Cloud Practitioner", org="Amazon Web Services", category="certification",
         description="Entry-level cloud certification validating understanding of AWS services, architecture and pricing. Widely recognised for first jobs.",
         tags=["AWS", "Cloud", "Cloud Computing", "Linux"],
         mode="remote", eligibility="Open to all, recommended for first-year students",
         deadline="2026-11-08", applyUrl="https://aws.amazon.com/education/aws-educate/", featured=True),
    dict(title="Microsoft Learn Azure Fundamentals", org="Microsoft", category="certification",
         description="Free Microsoft certification covering cloud concepts, Azure services, identity and security. Includes free exam vouchers for students.",
         tags=["Azure", "Cloud", "Security", "Cloud Computing"],
         mode="remote", eligibility="Open to all",
         deadline="2026-12-01", applyUrl="https://www.microsoft.com/en-in/learning"),
    dict(title="freeCodeCamp Full Stack Certification", org="freeCodeCamp", category="certification",
         description="Completely free, project-based curriculum covering HTML, CSS, JavaScript, React, Node and databases with 3000+ hours of material.",
         tags=["HTML", "CSS", "JavaScript", "React", "Node.js", "APIs", "Git"],
         mode="remote", eligibility="Open to all, self-paced",
         deadline="2026-12-31", applyUrl="https://www.freecodecamp.org/", featured=True),
    dict(title="Introduction to Machine Learning", org="Stanford University", category="course",
         description="Andrew Ng's foundational ML course covering supervised learning, neural networks and practical advice for ML projects.",
         tags=["Machine Learning", "Python", "Neural Networks", "Mathematics"],
         mode="remote", eligibility="Open to all, basic linear algebra helpful",
         deadline="2026-11-11", applyUrl="https://www.coursera.org/"),
    dict(title="CS50: Introduction to Computer Science", org="Harvard University", category="course",
         description="Harvard's flagship intro course covering C, Python, algorithms, data structures, SQL and web development.",
         tags=["C", "Python", "SQL", "Algorithms", "Web", "Git"],
         mode="remote", eligibility="Open to all, free audit",
         deadline="2026-12-15", applyUrl="https://cs50.harvard.edu/", featured=True),
    dict(title="Kaggle Learn Python / Data Science", org="Kaggle", category="course",
         description="Short hands-on micro-courses in Python, pandas, machine learning and SQL, each completable in a few hours.",
         tags=["Python", "Pandas", "SQL", "Machine Learning", "Data Visualisation"],
         mode="remote", eligibility="Open to all",
         deadline="2026-12-10", applyUrl="https://www.kaggle.com/learn"),
    dict(title="Git and GitHub Bootcamp", org="GitHub", category="workshop",
         description="Hands-on version control workshop covering branching, pull requests, conflict resolution and open-source collaboration.",
         tags=["Git", "Open Source", "Collaboration", "GitHub"],
         mode="remote", eligibility="Open to all",
         deadline="2026-10-28", applyUrl="https://education.github.com/"),
    dict(title="SQL for Data Analysis", org="Mode Analytics", category="course",
         description="Practical SQL course teaching joins, window functions and analytical queries through business datasets.",
         tags=["SQL", "Data Analytics", "PostgreSQL", "Statistics"],
         mode="remote", eligibility="Open to all",
         deadline="2026-11-19", applyUrl="https://www.kaggle.com/learn"),

    # ---------------- Competitions ----------------
    dict(title="HackerRank Skills Certification", org="HackerRank", category="certification",
         description="Employer-recognised skill certifications across Python, Java, problem solving and SQL. Badges appear directly on your profile.",
         tags=["Python", "Java", "SQL", "Algorithms", "Problem Solving"],
         mode="remote", eligibility="Open to all",
         deadline="2026-12-31", applyUrl="https://www.hackerrank.com/skills-directory", featured=True),
    dict(title="CodeChef Starters", org="CodeChef", category="competition",
         description="Weekly beginner-to-advanced programming contests with a public leaderboard and editorial-based learning loop.",
         tags=["C++", "Python", "Algorithms", "Data Structures", "Problem Solving"],
         mode="remote", eligibility="Open to all skill levels",
         deadline="2026-10-18", applyUrl="https://www.codechef.com/", featured=True),
    dict(title="LeetCode Weekly Contest", org="LeetCode", category="competition",
         description="Weekly algorithm contest aligned to technical interviews. Essential practice for product engineering roles.",
         tags=["Data Structures", "Algorithms", "Python", "C++", "SQL"],
         mode="remote", eligibility="Open to all",
         deadline="2026-10-19", applyUrl="https://leetcode.com/contest/"),
    dict(title="Kaggle Playground Series", org="Kaggle", category="competition",
         description="Monthly beginner machine-learning competitions with approachable datasets and active community discussion boards.",
         tags=["Python", "Machine Learning", "Pandas", "Data Visualisation", "Statistics"],
         mode="remote", eligibility="Open to all",
         deadline="2026-10-30", applyUrl="https://www.kaggle.com/competitions", featured=True),
    dict(title="TryHackMe Jr Penetration Tester", org="TryHackMe", category="certification",
         description="Hands-on guided cybersecurity pathway from networking fundamentals to web exploitation, in a browser-based lab.",
         tags=["Linux", "Networking", "Penetration Testing", "Security", "Python"],
         mode="remote", eligibility="Open to all, some Linux basics assumed",
         deadline="2026-12-05", applyUrl="https://tryhackme.com/"),
    dict(title="Hack The Box Pre Security", org="Hack The Box", category="certification",
         description="Entry-level offensive security certification covering web, network and container fundamentals through hands-on machines.",
         tags=["Linux", "Networking", "Security", "Penetration Testing", "Docker"],
         mode="remote", eligibility="Open to all",
         deadline="2026-11-22", applyUrl="https://www.hackthebox.com/"),

    # ---------------- Workshops ----------------
    dict(title="GitHub Student Developer Pack", org="GitHub", category="course",
         description="Free collection of developer tools, credits and benefits for verified students, including Copilot and cloud credits.",
         tags=["Git", "GitHub", "Cloud", "Open Source"],
         mode="remote", eligibility="Verified students aged 13+",
         deadline="2026-12-31", applyUrl="https://education.github.com/pack", featured=True),
    dict(title="Google Cloud Skills Boost (Free Tier)", org="Google Cloud", category="course",
         description="Guided cloud labs and short quests covering GCP fundamentals, with free monthly credits for new accounts.",
         tags=["GCP", "Cloud", "Kubernetes", "Cloud Computing"],
         mode="remote", eligibility="Open to all, free tier available",
         deadline="2026-12-15", applyUrl="https://www.cloudskillsboost.google/"),
    dict(title="DeepLearning.AI AI for Everyone", org="deeplearning.ai", category="course",
         description="Non-technical introduction to what AI can and cannot do, with practical advice on using AI in your own work.",
         tags=["AI", "Machine Learning", "Deep Learning"],
         mode="remote", eligibility="Open to all, no coding required",
         deadline="2026-11-27", applyUrl="https://www.deeplearning.ai/courses/"),
    dict(title="Arduino & IoT Hardware Workshop", org="Arduino Community", category="workshop",
         description="Hands-on workshop covering sensor interfacing, MQTT and cloud dashboards for connected devices.",
         tags=["IoT", "Arduino", "C++", "Python", "MQTT", "Embedded Systems"],
         mode="onsite", eligibility="All students, laptops provided if unavailable",
         deadline="2026-10-24", applyUrl="https://www.arduino.cc/education"),
    dict(title="UI/UX Design Bootcamp", org="Google Design", category="workshop",
         description="Practical design workshop covering Figma, design systems, user research and portfolio-ready case studies.",
         tags=["UI Design", "UX Design", "Figma", "Prototyping"],
         mode="remote", eligibility="Open to all",
         deadline="2026-11-05", applyUrl="https://www.coursera.org/"),
    dict(title="Public Speaking for Technical Presenters", org="TEDxYouth", category="workshop",
         description="Workshop on structuring technical talks, building narrative around a project and handling Q&A confidently.",
         tags=["Communication", "Public Speaking", "Leadership", "Presenting"],
         mode="remote", eligibility="Open to all",
         deadline="2026-10-30", applyUrl="https://www.ted.com/"),
    dict(title="Open Source Contribution Mentorship", org="Mozilla Community", category="workshop",
         description="Structured mentorship programme pairing new contributors with experienced maintainers on real bug fixes.",
         tags=["Open Source", "Git", "Community", "Mentorship"],
         mode="remote", eligibility="First-time contributors prioritised",
         deadline="2026-11-12", applyUrl="https://www.mozilla.org/community/"),
    dict(title="Intro to Flutter App Development", org="Google Developers", category="workshop",
         description="Live-code workshop building a cross-platform mobile app in Flutter with Firebase integration.",
         tags=["Flutter", "Dart", "Firebase", "Mobile Development"],
         mode="remote", eligibility="Basic programming knowledge",
         deadline="2026-10-26", applyUrl="https://developers.google.com/"),
    dict(title="Data Structures with JavaScript", org="freeCodeCamp", category="workshop",
         description="Workshop building and visualising core data structures in JavaScript to build algorithm intuition.",
         tags=["JavaScript", "Data Structures", "Algorithms"],
         mode="remote", eligibility="Open to all",
         deadline="2026-11-16", applyUrl="https://www.freecodecamp.org/"),

    # ---------------- Already closed (proves the "closed" state works) ----
    dict(title="Smart India Hackathon 2025", org="Government of India", category="hackathon",
         description="Previous edition of SIH. Shown to verify the platform correctly flags closed applications.",
         tags=["Python", "JavaScript", "IoT", "Machine Learning"],
         mode="onsite", eligibility="All UG/PG students across India",
         deadline="2025-11-20", applyUrl="https://www.sih.gov.in/"),
    dict(title="HackWithInfy 2026 (Round 1)", org="Infosys", category="hackathon",
         description="Closed round of HackWithInfy 2026, included to demonstrate deadline filtering.",
         tags=["Java", "Python", "SQL"],
         mode="onsite", eligibility="UG engineering students",
         deadline="2026-06-15", applyUrl="https://www.hackwithinfy.com/"),
    dict(title="Vidyarthi Vigyan Manthan 2025", org="VVM", category="competition",
         description="Previous year's examination, retained as an example of a closed listing.",
         tags=["Science", "Mathematics", "Reasoning"],
         mode="remote", eligibility="Class 9-12 students",
         deadline="2025-10-12", applyUrl="https://www.vvm.org/"),
]

def build_seed() -> list:
    """Fixed listings + rolling deadlines, resolved against today's date."""
    rows = [dict(r) for r in SEED_OPPORTUNITIES]
    today = date.today()
    for offset, row in _ROLLING:
        entry = dict(row)
        entry["deadline"] = (today + timedelta(days=offset)).isoformat()
        rows.append(entry)
    return rows

